// <auto-generated />
namespace PB.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201806070557392_newMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
